export const ADD_TODO_ITEMS = 'ADD_TODO_ITEMS';
export const EDITS_TODO_ITEMS = 'EDITS_TODO_ITEMS';
export const DELETES_TODO_ITEMS = 'DELETES_TODO_ITEMS'
export const TOGGLE_COMPLETE_TODO = "TOGGLE_COMPLETE_TODO";


export const LOADING_TODO_ITEMS = 'LOADING_TODO_ITEMS';
export const ERROR_TODO_ITEMS = 'ERROR_TODO_ITEMS';
